### ISSUE TITLE
Basic Auth not working

### ISSUE THREAD

**Issue by TPei** [s8sg/faas-flow-dashboard#1]
when setting basic_auth to true and providing the appropriate secrets, `list-flow-functions` fails with a `401: invalid credentials`.

I do get it to work if I replace `handler.go` lines 25-31 with a simple `httpReq.SetBasicAuth(my_user, my_password)`

From the debugging I've done I can see that the credentials are found (using non-existent secrets results in a different error) and can be read. Concerning the contents, I tried using both the ones that are created when setting up OpenFaaS on docker-swarm as well as creating new ones via `docker secrete create`, so they should be fine.

Platform:
docker-swarm on Docker version 18.09.0, build 4d60db4

**Comment by s8sg** [comment]
@TPei I added some change at https://github.com/s8sg/faas-flow-dashboard/tree/issue-1
would you be able to give it a try ?

 I'm not very sure what is causing the problem.

**Comment by TPei** [comment]
yeah, seems to be working @s8sg

**Comment by s8sg** [comment]
Thank you for the confirmation. I've merged it.
